//User 
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const ADD_USERS = 'ADD_USERS';
export const START_ADDING_USER_REQUEST = 'START_ADDING_USER_REQUEST';
export const ADD_USER = 'ADD_USER';
export const START_CREATE_USER_REQUEST = 'START_CREATE_USER_REQUEST';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

//Coach related
export const FETCH_COACHPOST_REQUEST = 'FETCH_COACHPOST_REQUEST';
export const ADD_COACH_POSTS = 'ADD_COACH_POSTS';
export const SELECT_USER = 'SELECT_USER';

//Posts and comments
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_POST = 'ADD_POST';

//following/followers
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const START_UNFOLLOW_REQUEST = 'START_UNFOLLOW_REQUEST';
export const FOLLOW_USER = 'FOLLOW_USER';
export const START_FOLLOW_REQUEST = 'START_FOLLOW_REQUEST';
export const ADD_FOLLOWING = 'ADD_FOLLOWING';
export const FETCH_FOLLOWING_REQUEST = 'FETCH_FOLLOWING_REQUEST';
export const ADD_FOLLOWERS = 'ADD_FOLLOWERS';
export const FETCH_FOLLOWERS_REQUEST = 'FETCH_FOLLOWERS_REQUEST';

//Other
export const ERROR = 'ERROR';